name: Avoda.HK
favicon: null
layout_spectrum: 0.40184
typography_spectrum: 0.13933
title: Genuinely Professional Chinese Payment Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: AC-160115-001
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#383838'
    - '#696969'
    - '#959595'
  brandStrength: 0.6671456058975309
  lightness: 0.842689789365977
  saturation: 0.5120895304717124
  rhythmicContrast: 0.5634515604469925
purpose: []
