name: Avoda.HK
favicon: null
layout_spectrum: 0.40054
typography_spectrum: 0.64796
title: Genuinely Professional Chinese Payment Consultant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: AC-160115-001
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#5388bc'
    - '#404f78'
    - '#dbaaad'
    - '#fefefc'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
